apiVersion: skaffold/v2beta20
kind: Config
metadata:
  name: basic-flask-application
build:
  artifacts:
  - image: basic-flask-application
    context: .
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - deployment.yaml