apiVersion: apps/v1
kind: Deployment
metadata:
  name: basic-flask-application
spec:
  replicas: 1
  selector:
    matchLabels:
      app: basic-flask-application
  template:
    metadata:
      labels:
        app: basic-flask-application
    spec:
      containers:
      - name: basic-flask-application
        image: <your-dokckerhub-username>/basic-flask-application:latest
        ports:
        - containerPort: 8080
