apiVersion: v1
kind: Service
metadata:
  name: basic-flask-application
spec:
  selector:
    app: basic-flask-application
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
